### ISSUE TITLE
ValidationError: 'port' is required

### ISSUE THREAD

**Issue by kylebolstad** [bigcommerce/channels-app#14]
There seems to be an issue with specifying the port. I see some possible talk of it in the netlify forums. Is this a known issue or is my particular setup somehow configured incorrectly? I am pretty certain I followed the instructions properly. They were very clearly written!

```
netlify -v
netlify-cli/2.17.0 darwin-x64 node-v10.16.3

yarn netlify:dev
yarn run v1.16.0
$ netlify dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with undefined

◈ Lambda server is listening on 34567
ValidationError: 'port' is required.
    at validateParameters (~/.nvm/versions/node/v10.16.3/lib/node_modules/netlify-cli/node_modules/wait-port/lib/validate-parameters.js:13:20)
    at Promise (~/.nvm/versions/node/v10.16.3/lib/node_modules/netlify-cli/node_modules/wait-port/lib/wait-port.js:183:9)
    at new Promise (<anonymous>)
    at waitPort (~/.nvm/versions/node/v10.16.3/lib/node_modules/netlify-cli/node_modules/wait-port/lib/wait-port.js:173:10)
    at startProxy (~/.nvm/versions/node/v10.16.3/lib/node_modules/netlify-cli/src/commands/dev/index.js:169:9)
    at DevCommand.run (~/.nvm/versions/node/v10.16.3/lib/node_modules/netlify-cli/src/commands/dev/index.js:344:31)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kylebolstad** [comment]
It does indeed look like `netlify v2.17.0` has some for issues. Downgrading to `netlify v2.16.0` at least gets `localhost:8888` up and running. However, now I get:

```
Request from ::1: GET /.netlify/functions/bigcommerce_proxy_channels?path=/
Error: {}
Response with status 500 in 50 ms.

**Comment by juanpprieto** [comment]
Same issue here.

**Comment by zhex900** [comment]
This is what I did

I updated `netlify.toml with this

```
[dev]
    framework = "#custom"
    command = "yarn start"
    targetPort = 3000
    publish = "packages/app-react/build" # If you use a _redirect file, provide the path to your static content folder
    functions = "packages/functions-netlify/build"
```
